### ISSUE TITLE
[suggestion] Update minio to Traefik v.2

### ISSUE THREAD

**Issue by Underknowledge** [funkypenguin/geek-cookbook#200]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I recently googled how to serve static files with træfik. in short, you don't. But the folks are using min.io objects. 
Another google search later I stumbled on the cookbook I used quite a few times already. 
oh-no.jpg. Its [tæefik v.1 ](https://geek-cookbook.funkypenguin.co.nz/recipes/minio) time to act!

**Describe the solution you'd like**
Control and api on 2 domains

**Describe alternatives you've considered**

![shoob](https://cdn.discordapp.com/emojis/886795094139740171.png?size=80)

**Teachability, Documentation, Adoption, Migration Strategy**
already tried my luck but failed. Maybe a starting point for someone else 

docker-compose.yml
```yaml
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    expose:
      - 9000
      - 9001
    volumes:
        - /opt/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://mgnt-s3.${DOMAINNAME}
      MINIO_SERVER_URL: https://objects.${DOMAINNAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - traefik
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik 
      # MINIO api
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.rule=Host(`objects.${DOMAINNAME}`)
      # MINIO console
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      - traefik.http.routers.minio-console.rule=Host(`mgnt-s3.${DOMAINNAME}`)
``` 

with this config I only get a bad gateway.
I could see that my issue comes from this middleware. 

 traefik.yml
```yaml
api:
  dashboard: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: acame@underknowledge.cc
      storage: /etc/traefik/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
http:
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

```
